// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.intent.betbull.platform.stub.entity;

import com.intent.betbull.platform.stub.entity.MarketDetail;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MarketDetail_Roo_Configurable {
    
    declare @type: MarketDetail: @Configurable;
    
}
